#!/bin/bash
# generate_restore_script.sh — writes restore.sh into an app folder
# Deployed to: /usr/local/bin/generate-restore-script.sh
#
# Called by maybe_generate_restore_script.sh (and optionally directly).
# Inherits LOG_FILE from the calling process environment.
#
# Usage: generate_restore_script.sh APP_DIR ZFS_DATASET APP_LABEL

APP_DIR="$1"
ZFS_DATASET="$2"
APP_LABEL="$3"
RESTORE_SCRIPT="${APP_DIR}restore.sh"
GEN_DATE=$(date '+%Y-%m-%d %H:%M:%S')

log_msg() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "${LOG_FILE:-/dev/null}"
}

# Note on heredoc escaping (delimiter RESTORE_EOF is unquoted, so bash expands variables):
#   ${VAR}   — expands at GENERATION time   (embeds a value into the script)
#   \${VAR}  — expands at RUNTIME           (written as ${VAR} in restore.sh)
#   \$(cmd)  — expands at RUNTIME           (written as $(cmd) in restore.sh)
#   \\       — produces a single \          (used to preserve line-continuation backslashes)

cat > "$RESTORE_SCRIPT" << RESTORE_EOF
#!/bin/bash
# Auto-generated restore script for ${APP_LABEL}
# Generated by app-backup.sh on ${GEN_DATE}
#
# Reads app.conf and source_*.conf from ${APP_DIR%/}/ at runtime,
# so SSH and path details stay current without regeneration.
# Delete this file and run app-backup.sh again only if the restore logic needs updating.

RESTORE_LOG="/var/log/restore_run.log"
APP_DIR="${APP_DIR%/}"

log_msg() {
    echo "[\$(date '+%Y-%m-%d %H:%M:%S')] [RESTORE] \$1" | tee -a "\${RESTORE_LOG}"
}

# Load app config
source <(tr -d '\r' < "\${APP_DIR}/app.conf")

echo "Restore helper for : \${APP_NAME}"
echo "ZFS dataset        : \${ZFS_DATASET}"
echo ""

# List available snapshots newest-first (tac reverses the creation-sorted list)
mapfile -t SNAPSHOTS < <(
    zfs list -t snapshot -H -o name -s creation -r "\${ZFS_DATASET}" 2>/dev/null \\
    | grep "^\${ZFS_DATASET}@" \\
    | tac
)

if [[ \${#SNAPSHOTS[@]} -eq 0 ]]; then
    echo "No snapshots found for \${ZFS_DATASET}."
    exit 1
fi

echo "Available snapshots (newest first):"
for i in "\${!SNAPSHOTS[@]}"; do
    printf "  [%d] %s\n" "\$((i+1))" "\${SNAPSHOTS[\$i]}"
done
echo "  [Enter] Latest: \${SNAPSHOTS[0]}"
echo ""

read -rp "Select snapshot (1-\${#SNAPSHOTS[@]}, or Enter for latest): " SEL

if [[ -z "\${SEL}" ]]; then
    SNAP="\${SNAPSHOTS[0]}"
elif [[ "\${SEL}" =~ ^[0-9]+\$ ]] && [[ "\${SEL}" -ge 1 && "\${SEL}" -le \${#SNAPSHOTS[@]} ]]; then
    SNAP="\${SNAPSHOTS[\$((SEL-1))]}"
else
    echo "Invalid selection."
    exit 1
fi

SNAP_SHORT="\${SNAP##*@}"

echo ""
echo "Selected       : \${SNAP}"
echo "Restore target : remote hosts defined in \${APP_DIR}/source_*.conf"
echo ""
echo "[WARNING] This will overwrite live data on the remote host(s) with snapshot data."
echo ""
read -rp "Are you sure? (y/N): " CONFIRM
[[ "\${CONFIRM}" != "y" ]] && echo "Aborted." && exit 0

# Open air-gap
log_msg "Opening air-gap for restore of \${APP_NAME} from \${SNAP}"
/usr/local/bin/airgap-link.sh open
sleep 3

shopt -s nullglob
RESTORE_FAILED=0

for SOURCE_CONF in "\${APP_DIR}"/source_*.conf; do
    [[ -f "\${SOURCE_CONF}" ]] || continue

    unset SOURCE_NAME REMOTE_PATH LOCAL_SUBDIR SRC_SSH_USER SRC_SSH_HOST SRC_SSH_PORT
    source <(tr -d '\r' < "\${SOURCE_CONF}")

    EFF_SSH_USER="\${SRC_SSH_USER:-\${SSH_USER}}"
    EFF_SSH_HOST="\${SRC_SSH_HOST:-\${SSH_HOST}}"
    EFF_SSH_PORT="\${SRC_SSH_PORT:-\${SSH_PORT:-22}}"

    # Path into the snapshot via the ZFS magic .zfs directory.
    # This is a virtual read-only view — no clone is created and no cleanup is needed.
    SNAP_DIR="/\${ZFS_DATASET}/.zfs/snapshot/\${SNAP_SHORT}"
    [[ -n "\${LOCAL_SUBDIR}" ]] && SNAP_DIR="\${SNAP_DIR}/\${LOCAL_SUBDIR}"

    log_msg "Restoring \${SOURCE_NAME}: \${SNAP_DIR}/ → \${EFF_SSH_USER}@\${EFF_SSH_HOST}:\${REMOTE_PATH}"

    # ---------------------------------------------------------------------------
    # RSYNC RESTORE
    # Source (local) : \${SNAP_DIR}/   (read-only snapshot contents, no cleanup needed)
    # Destination    : \${EFF_SSH_USER}@\${EFF_SSH_HOST}:\${REMOTE_PATH}
    #
    # Adjust ssh options or add --exclude flags below as needed for your environment.
    # ---------------------------------------------------------------------------
    rsync -az \\
        -e "ssh -p \${EFF_SSH_PORT} -o ConnectTimeout=15" \\
        "\${SNAP_DIR}/" \\
        "\${EFF_SSH_USER}@\${EFF_SSH_HOST}:\${REMOTE_PATH}"

    if [[ \$? -eq 0 ]]; then
        log_msg "[SUCCESS] \${SOURCE_NAME} pushed to \${EFF_SSH_HOST}:\${REMOTE_PATH}."

        # Optional: prompt for a post-restore import command (e.g. database reload)
        if [[ "\${REMOTE_PATH}" == *.sql ]]; then
            echo ""
            echo "Detected .sql destination. Run a remote import command?"
            echo "  Example: docker exec -i <container> mysql -u <user> -p<password> <db> < \${REMOTE_PATH}"
            read -rp "  Enter import command (or Enter to skip): " IMPORT_CMD
            if [[ -n "\${IMPORT_CMD}" ]]; then
                ssh -n -p "\${EFF_SSH_PORT}" "\${EFF_SSH_USER}@\${EFF_SSH_HOST}" "\${IMPORT_CMD}"
            fi
        fi
    else
        log_msg "[ERROR] Restore failed for \${SOURCE_NAME}."
        RESTORE_FAILED=1
    fi

done

# Close air-gap
/usr/local/bin/airgap-link.sh close

# No explicit cleanup needed: .zfs/snapshot/ is a virtual read-only directory;
# accessing it creates no clone and leaves no residual data on the backup server.
echo ""
if [[ \${RESTORE_FAILED} -eq 0 ]]; then
    log_msg "Restore complete — all sources pushed successfully."
else
    log_msg "Restore finished with errors — check \${RESTORE_LOG} for details."
fi
RESTORE_EOF

chmod 750 "$RESTORE_SCRIPT"
log_msg "  [INFO] Restore script generated: ${RESTORE_SCRIPT}"
