SOURCE_NAME="bookstack_files"
REMOTE_PATH="/opt/bookstack"
LOCAL_SUBDIR="app_data" # relative to ZFS dataset mount if syncing folder it will be created as subdir so if syncing whole dataset leave empty
EXCLUDES_FILE="excludes_02.txt"
# SSH overrides (leave blank to inherit from app.conf):
# SRC_SSH_USER=""
# SRC_SSH_HOST=""
# SRC_SSH_PORT=""
# SRC_SSH_IDENTITY=""
